global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'nest-api'
    static_configs:
      - targets: ['api:3333']
    metrics_path: /metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']   
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:9187']       
